### ISSUE TITLE
Error with a different N_LAGS

### ISSUE THREAD

**Issue by justinhou95** [niklaswalter/Randomised-Signature-TimeSeries-Generation#1]
Hi Francesca,

I encounter an error when setting `N_LAGS=60`. 

The error seems to be caused by
`
        self.readouts = nn.ModuleList([nn.Linear(self.reservoir_dim, self.output_dim, device=DEVICE)
                                       for i in range(10)])
`
in `NeuralSDEGenerator`, which hardcodes `n_lag = 10`. So it only works when `n_lag = 10`.

I solved it by initializing the `self.readouts` with `n_lag` with the following code:
`
        self.readouts = nn.ModuleList([nn.Linear(self.reservoir_dim, self.output_dim, device=DEVICE)
                                       for i in range(10)])
`

Hope this helps if anyone is facing a similar error :) 

Best,
Songyan

**Comment by niklaswalter** [comment]
Hi! 

Thanks a lot! Of course, it seems like I hardcoded it for the final experiments. I fixed this now. 

Best, 
Niklas
